image: python:3.8

stages:
  - test

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install poetry
  - poetry install

Unit Tests:
  stage: test
  script:
    - poetry run pytest 








